### ISSUE TITLE
Clicking on the anchorRef is not closing the ControlledMenu

### ISSUE THREAD

**Issue by aravindsurya77** [szhsin/react-menu#56] opened 2021-02-12 01:10 UTC
Hey @szhsin,

I was trying to implement a ControlledMenu and came across this issue when, the menu is open and clicking on the anchorRef element is not closing it. In fact I see, it closes and opens again. 

Here is the [code sandbox example](https://codesandbox.io/s/serene-minsky-g6xeh?file=/src/App.js).

**Comment by szhsin** [comment] 2021-02-13 06:18
Hi @aravindsurya77 , thanks for your feedback.

`Menu` or `ControlledMenu` relies on the `onBlur` event to determine whether it should be closed. 

The `onBlur` event fires when a user clicks something in the page outside the menu, which means `onBlur` also fires when the anchorRef element is clicked.

Ideally, when anchorRef element is clicked, we should not close menu in response to `onBlur` but let the subsequent `onClick` event of anchorRef element to close it, similar to what is done in your example, so we won't see the menu close and open again.

The `onBlur` event has a `relatedTarget` that helps determine which element receives focus. However, `relatedTarget` is not correctly set to the anchorRef element in Firefox, Safari and IE11. Some discussion can be found at: https://github.com/facebook/react/issues/2011
As I tested it, the issue is still not resolved in the latest Firefox/Safari with React 17.

[Here is an example](https://codesandbox.io/s/controlledmenu-toggle-open-jd3u4) to workaround the issue using a timer to skip subsequent `onClick` on anchorRef element after an `onBlur` event on menu. The solution is not ideal, but it works well and keeps code consistent across all browsers.

`Menu` uses this solution internally. If you use `ControlledMenu`, you need to handle this situation in your code.
Please feel free to discuss this issue further if you have any questions.

**Closed** 2021-02-22 08:10 UTC
