### ISSUE TITLE
Menu Persists During Page Transition

### ISSUE THREAD

**Issue by danglez83** [szhsin/react-menu#1067] opened 2023-08-30 20:10 UTC
React/React-dom version: 18.2.4
React-Menu version: 4.0.3

## To Reproduce

1. Create a basic menu
2. Click a menu item that navigates to another page within the app using react router
3. Our modal is displayed while loading the new page, but the menu is persisted until the page is fully loaded

## Expected behavior
I would expect the menu to disappear before transitioning to the new page.

## Code snippets/CodeSandbox examples/Screenshots
![menu persists](https://github.com/szhsin/react-menu/assets/42001195/e3cf44af-22fc-4c13-aab2-f956be4c6241)
![menu persists](https://github.com/szhsin/react-menu/assets/42001195/325faddc-2db5-48a8-b340-af2f39208c3b)

**Comment by szhsin** [comment] 2023-09-02 08:31
Hey @danglez83 , we have a [react router example](https://codesandbox.io/s/react-menu-router-v6-wxi1uf?file=/src/App.js) which works fine. If you call `closeMenu` from `FocusableItem` before page transition, menu would close.

**Comment by danglez83** [comment] 2023-09-02 12:29
Hey @szhsin, I am using just `MenuItem` components in my project as opposed to `FocusableItem` (don't use the link styles) and can't seem to get it to work as expected. My component structure looks essentially like this:

`<MenuItem {...props} disabled={menuDisabled}>{children}</MenuItem>`

I even tried setting the `toggleMenu(false)` on the menu state when a _nav_ menu item is clicked:
`<Menu {...menuState} anchorRef={ref} ...>{children}</Menu>`

Any pointers?

**Comment by szhsin** [comment] 2023-09-02 13:12
Calling `toggleMenu(false)` should close the menu, unless it is not called in a desirable event. 

We also have a [react-router example](https://codesandbox.io/s/react-menu-react-router-example-dw4ku?file=/App.js) that works with `MenuItem` (check the "About" link). It's not quite different from `FocusableItem`, as `MenuItem` toggles off menu in response to the onClick event.

**Comment by szhsin** [comment] 2023-09-11 01:13
Hey @danglez83 , has the problem been resolved, should I close the ticket?

**Comment by danglez83** [comment] 2023-09-11 12:26
Hey @szhsin, unfortunately I still cannot get it to work as expected. Trying to get to the root of the issue.

**Comment by danglez83** [comment] 2023-09-14 16:27
@szhsin some more insight on our app structure:

`<Suspense fallback={<LoadingScreen />}>
      <ApplicationHeader />
      <BreadcrumbContext.Provider value={breadcrumbStore}>
        <Box width={1} flex="1">
          <Switch>
            <Route exact path={ROUTES.LOGIN_REDIRECT.url} component={Nothing} />
            <AuthenticatedRoute component={BreadcrumbSlot} />
          </Switch>
`
Our routes are all wrapped by react's Suspense component, which renders a loading modal as soon as the transition starts. This is what is being displayed beneath the menu before the menu eventually disappears (closes).

**Comment by szhsin** [comment] 2023-09-17 12:19
Not sure what's the issue, but there might be something we can check:
1. If `ControlledMenu` were used, we can console log the `onClose` event and check whether the event fired before or after page transitions. Similarly, use `onMenuChange` event for `Menu` component.
2. Is your menu rendered outside the Suspense boundary? If yes, try to move it inside Suspense. When any of the routes suspends, React will hide the menu and render the loading fallback.

**Comment by danglez83** [comment] 2023-09-18 12:53
Hey @szhsin ok, I had actually done this before, but repeated just for peace of mind. The order of operations is like this based on console logs:

- menu item clicked
- navigation
- onClose fired

The menu is rendered within the Suspense, BUT it has the portal prop set to true (many cases within our app need the menu _break the bounds_ of the smaller parent container, so we use that prop.

**Comment by szhsin** [comment] 2023-09-18 13:17
The `onClose` event has a `reason` prop, can you please confirm what the value is?
``` ts
type CloseReason = 'click' | 'cancel' | 'blur' | 'scroll';
```
Also, does "menu item clicked" represent exactly the `onClick` event on `MenuItem` component?

**Comment by szhsin** [comment] 2023-09-18 13:24
Just a guess, the link underneath a menu item could have called `stopPropagation` and that menu item didn't receive a click event. Menu eventually closed due to losing focus after page transition has completed.

**Comment by danglez83** [comment] 2023-09-18 13:24
The `reason` is returning, 'close'

The "menu item clicked" was logged via:

<Menu
          {...menuState}
          anchorRef={ref}
          onClose={(e) => console.log(`menu item clicked (${e.reason})`) as any || toggleMenu(false)}

**Comment by szhsin** [comment] 2023-09-18 13:39
Well, that's strange as `reason` can only be one of the four values.

Could you log the `onItemClick` event to check whether it was fired?
```diff
<Menu
   {...menuState}
   anchorRef={ref}
+ onItemClick={(e) => console.log(menu item clicked)}
   onClose={(e) => console.log(menu item closed (${e.reason})) as any || toggleMenu(false)}
```

**Comment by danglez83** [comment] 2023-09-18 13:40
My apologies, it is close, not click - typo

**Comment by danglez83** [comment] 2023-09-18 13:44
ok, here is my output based on the following:

```
          onItemClick={() => console.log('onItemClick')}
          onClose={e =>
            (console.log('onClose', e.reason) as any) || toggleMenu(false)
          }
```
onItemClick
onClose, click

**Comment by szhsin** [comment] 2023-09-18 14:01
Thanks for providing the info. The events all look fine and no clue of anything goes wrong here.

Checked again your first video, it looks like something was blocking the main thread for a moment when routes were switching. Maybe it was downloading and parsing a large chunk of JavaScript code?

**Comment by danglez83** [comment] 2023-09-18 14:04
No problem.

The only thing that occurs during the switch is storing the previous Url in state. Not sure if you saw above, but I do have the portal prop set; if this is not set, the issue does not seem to occur.

**Comment by szhsin** [comment] 2023-09-22 08:52
I did notice you mentioned portal, but didn't think it played a role as I assume React should handle portal no differently in terms of events. This is from [React website](https://react.dev/reference/react-dom/createPortal):
> A portal only changes the physical placement of the DOM node. **In every other way, the JSX you render into a portal acts as a child node of the React component that renders it.** For example, the child can access the context provided by the parent tree, and events still bubble up from children to parents according to the React tree.

Your code had `<Suspense/>`, wasn't it be used with `React.lazy` for code splitting and lazy-loading components?

**Comment by szhsin** [comment] 2023-09-25 07:32
Hey @danglez83 I'm trying to replicate the issue on my end and i need a bit more information. 

According to [React website](https://react.dev/reference/react/Suspense), suspense currently only supports two use cases:
> Only Suspense-enabled data sources will activate the Suspense component. They include: 
> - Data fetching with Suspense-enabled frameworks like [Relay](https://relay.dev/docs/guided-tour/rendering/loading-states/) and [Next.js](https://nextjs.org/docs/getting-started/react-essentials)
> - Lazy-loading component code with [lazy](https://react.dev/reference/react/lazy)

You said "show a fallback (loading modal) while the transition is happening", could you point out what caused `<Suspense/>` to show a fallback in your use case, if the reason was not loading code-split components or data fetching?

**Comment by szhsin** [comment] 2023-10-01 10:53
Mystery solved. It is a known issue of React, see: https://github.com/facebook/react/issues/26612

In short, Suspense cannot hide portal when the portal is not a direct child of Suspense.

An example that replicates the issue: https://codesandbox.io/s/react-menu-1067a-sfgmrj

Before the issue is fixed in React, there are some workarounds:

1. Move menu up the React tree and make it a direct child of Suspense: https://codesandbox.io/s/react-menu-1067b-fwpqfz
2. Use a menu's [portal.target](https://github.com/szhsin/react-menu/blob/a9246f82833501b5a11eef3773366aa5e9d5dcc2/types/index.d.ts#L293) to portal the menu to a node which is WITHIN Suspense boundary, and high enough in the DOM for the menu to break out any overflow. https://codesandbox.io/s/react-menu-1067c-m6tmry

**Comment by szhsin** [comment] 2023-11-27 12:19
Closing it as caused by an upstream issue (React).

**Closed by szhsin** 2023-11-27 12:19 UTC
