### ISSUE TITLE
Default styles are not applied 

### ISSUE THREAD

**Issue by exaucae** [szhsin/react-menu#415] opened 2022-02-08 03:12 UTC
I ran the simple example below [from the docs](https://szhsin.github.io/react-menu). It renders basic html lists, without any styling. Suspecting the stylesheets imports should be done somewhere else, I moved them to the  entrypoint file and bunch of other places, in vain. Am I missing something trivial there?  

````js
import React from 'react';
import {
    Menu,
    MenuItem,
    MenuButton
} from '@szhsin/react-menu';
import '@szhsin/react-menu/dist/index.css';
import '@szhsin/react-menu/dist/transitions/slide.css';

export default function Example() {
    return (
        <Menu menuButton={<MenuButton>Open menu</MenuButton>} transition>
            <MenuItem>New File</MenuItem>
            <MenuItem>Save</MenuItem>
            <MenuItem>Close Window</MenuItem>
        </Menu>
    );
}

````

Library version: @szhsin/react-menu: 2.3.4

**Comment by szhsin** [comment] 2022-02-08 07:27
Hi @exaucae , 
Your code looks good to me. Just having a check if your stack has been configured to support importing `css` files in JavaScript. 
If you use **Create React App** or **Next.js,** it should have the support out of box.
If you have a custom webpack config, make sure it includes the `'style-loader', 'css-loader'` https://webpack.js.org/guides/asset-management/#loading-css

If you don't use any of the above, try to copy the styles in `'@szhsin/react-menu/dist/core.css'` or `'@szhsin/react-menu/dist/index.css'` into your own CSS files or CSS-in-JS solution.

**Comment by exaucae** [comment] 2022-02-08 12:32
Thanks for the pointers, 
Yes, I have a custom Webpack config, with the proper loaders already set up. Other stylesheets are applied. 
Copy-pasting style-sheets content doesn't change much things. That's really odd now.

**Comment by szhsin** [comment] 2022-02-13 13:32
Looks like an isolated case and most likely caused by your environment setup. Without further details it's hard to figure out what was going on. Close it for now.

**Closed by szhsin** 2022-02-13 13:32 UTC
