### ISSUE TITLE
Expected Focus on menu close w/controlled menu

### ISSUE THREAD

**Issue by FBNitro** [szhsin/react-menu#1153] opened 2023-11-16 21:21 UTC
React/React-dom version: 18.x
React-Menu version: 3.5.3 & 4.1.0

When using a controlled component, I've noticed that when the menu closes it does not return focus to the component that initiated the menu from appearing.  I'm not sure if this could be considered a bug, or if the expectation is that the consumer writes code to set focus back to the triggering component.

https://szhsin.github.io/react-menu-v3#controlled-menu

Tab to the button, hit the spacebar, pick an item using keyboard.  ActiveElement is set to something other than the button.

If you use the basic button: https://szhsin.github.io/react-menu#basic-menu  You can see that the button regains focus when the menu closes if you repeat the same steps.

So, do we consider this a bug, or is it intentional?

**Comment by szhsin** [comment] 2023-11-18 11:09
This is by design for a few reasons:

- A controlled menu doesn't necessary have a focusable anchor element. When it's used as a context menu, the anchor is merely a coordinate on the screen. When it's used as a hover menu, the anchor could be a non-focusable element, or event a  virtual rectangle on the screen.
- Consumer might listen to the `onClose` event of a controlled menu and skip closing the menu under certain conditions. In this case, it doesn't make sense to set focus back to another element.

If required, a consumer could restore focus to a desired element after the menu has been closed:
```jsx
<ControlledMenu
  anchorRef={ref}
  onClose={(e) => {
    setOpen(false);
    if (e.key) anchorRef.current.focus();
  }}
>
```

**Closed by szhsin** 2023-11-18 11:09 UTC
Labels: question
